# Generated by Django 2.1.5 on 2019-03-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(default='No description given', max_length=100)),
            ],
        ),
    ]
