# Generated by Django 2.1.7 on 2019-03-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('person_count', models.CharField(max_length=30)),
                ('gstin', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField()),
                ('room_no', models.CharField(max_length=7)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('days_count', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('room_no_2', models.CharField(blank=True, max_length=7, null=True)),
                ('check_in_2', models.DateField(blank=True, null=True)),
                ('check_out_2', models.DateField(blank=True, null=True)),
                ('days_count_2', models.IntegerField(default=0)),
                ('rate_2', models.IntegerField(default=0)),
                ('room_no_3', models.CharField(blank=True, max_length=7, null=True)),
                ('check_in_3', models.DateField(blank=True, null=True)),
                ('check_out_3', models.DateField(blank=True, null=True)),
                ('days_count_3', models.IntegerField(default=0)),
                ('rate_3', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('is_gst', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(default='No description given', max_length=100)),
            ],
        ),
    ]
