# Generated by Django 2.1.5 on 2019-03-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=13)),
                ('person_count', models.CharField(max_length=30)),
                ('gstin', models.CharField(blank=True, max_length=30, null=True)),
                ('room_no', models.CharField(max_length=7)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('days_count', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
