# Generated by Django 2.1.7 on 2019-03-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='check_in_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='check_out_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='days_count_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rate_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='room_no_2',
        ),
    ]
