# Generated by Django 2.1.7 on 2019-03-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_invoice_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='check_in',
            field=models.DateField(verbose_name='Room In'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='check_in_2',
            field=models.DateField(blank=True, null=True, verbose_name='Room In 2'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='check_in_3',
            field=models.DateField(blank=True, null=True, verbose_name='Room In 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='check_out',
            field=models.DateField(verbose_name='Room Out'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='check_out_2',
            field=models.DateField(blank=True, null=True, verbose_name='Room out 2'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='check_out_3',
            field=models.DateField(blank=True, null=True, verbose_name='Room out 3'),
        ),
    ]
