# Generated by Django 2.1.5 on 2019-03-19 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 18, 11, 46, 520977, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_gst',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
