# Generated by Django 2.1.7 on 2019-03-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190323_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='check_in_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='check_in_3',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='check_out_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='check_out_3',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='days_count_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='days_count_3',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rate_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rate_3',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='room_no_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='room_no_3',
        ),
        migrations.AddField(
            model_name='invoice',
            name='check_in_02',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='check_in_03',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='check_out_02',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='check_out_03',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='days_count_02',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='days_count_03',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rate_02',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rate_03',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='room_no_02',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='room_no_03',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
