# Generated by Django 2.1.7 on 2019-03-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190323_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='check_in_02',
            new_name='check_in_2',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='check_in_03',
            new_name='check_in_3',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='check_out_02',
            new_name='check_out_2',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='check_out_03',
            new_name='check_out_3',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='days_count_02',
            new_name='days_count_2',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='days_count_03',
            new_name='days_count_3',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='rate_02',
            new_name='rate_2',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='rate_03',
            new_name='rate_3',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='room_no_02',
            new_name='room_no_2',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='room_no_03',
            new_name='room_no_3',
        ),
    ]
